# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            caumine的博客
tagline:          'caumine'
description:      '---'
url:              https://kumine.github.io/
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'caumine'
  url:            https://kumine.github.io/

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/kumine/kumine.github.io
